# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Check the root and app build.gradle
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/EZRecipes" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      # Don't update Kotlin since it must be compatible with the current Compose release
      # See: https://developer.android.com/jetpack/androidx/releases/compose-kotlin
      - dependency-name: "org.jetbrains.kotlin.android"
  # Check Gemfile
  - package-ecosystem: "bundler"
    directory: "/EZRecipes"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
