# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Split the unit and instrumentation tests into separate jobs to improve CI performance
jobs:
  unit-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./EZRecipes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod u+x gradlew

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run unit tests
        run: bundle exec fastlane android test

  ui-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 29, 31, 33 ]

    defaults:
      run:
        working-directory: "./EZRecipes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod u+x gradlew

#      - name: Install Ruby & Fastlane
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true
#
#      - name: Run instrumented tests
#        run: bundle exec fastlane android ui_test api:${{ matrix.api-level }}
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          working-directory: "./EZRecipes"
          script: ./gradlew connectedAndroidTest

      # The test results are shown as a webpage instead of on the command line
      - name: Upload reports
        if: always() # show reports even if the previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.api-level }}
          path: ./EZRecipes/app/build/reports
