# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 29, 31, 33 ]

    defaults:
      run:
        working-directory: './EZRecipes'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod u+x gradlew

      - name: Install Fastlane
        run: bundle install

      - name: Run unit tests
        run: bundle exec fastlane android test

#      - name: Run instrumented tests
#        run: bundle exec fastlane android ui_test
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          working-directory: "./EZRecipes"
          script: ./gradlew connectedAndroidTest

      # The test results are shown as a webpage instead of on the command line
      - name: Upload Reports
        if: always() # show reports even if the previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: reports-${{ matrix.api-level }}
          path: ./EZRecipes/app/build/reports
